### ISSUE TITLE
cd_dist.so with PointSetGeneration compilation doesn't make sense

### ISSUE THREAD

**Issue by ruida** [nywang16/Pixel2Mesh#10]
I compile PointSetGeneration with make (Ubuntu).  I only see the following .so files being generated.   There is no any cd_dist.so.    How do you compile PointSetGeneration to get the cd_dist.so file? 

Thanks. 

root@6bf78506a78b:/Pixel2Mesh/PointSetGeneration/depthestimate# ls
BatchFetcher.py      render_balls_so.so  show3d_balls.py    tf_nndistance.py    tf_nndistance_g.cu.o  train_nn.py
render_balls_so.cpp  show3d.py           tf_nndistance.cpp  tf_nndistance_g.cu  tf_nndistance_so.so   visualizeptexample.v.py

**Comment by hank0982** [comment]
You can rename tf_nndistance_so.so to cd_dist.so and replace original cd_dist.so with that

**Comment by ruida** [comment]
I do replacement, but still get the following error.  Compile PointSetGeneration with make good enough?  Any changes in PointSetGeneration?   Thanks.  

/Pixel2Mesh/pixel2mesh# python demo.py --image utils/examples/ 
Traceback (most recent call last):
  File "demo.py", line 3, in <module>
    from models import GCN
  File "/Pixel2Mesh/pixel2mesh/models.py", line 3, in <module>
    from losses import *
  File "/Pixel2Mesh/pixel2mesh/losses.py", line 2, in <module>
    from cd_dist import *
ImportError: dynamic module does not define init function (initcd_dist)

**Comment by XuXianbing** [comment]
after replacement, when I run the demo, I find these problem: "undefined symbol: _ZTIN10tensorflow8OpKernelE", This is because when compiling code with g++, it is not used by the tensorflow_framework.so dynamic library. But I don't know how to use it. Have you encountered this problem?

**Comment by qui22** [comment]
> I do replacement, but still get the following error. Compile PointSetGeneration with make good enough? Any changes in PointSetGeneration? Thanks.
> 
> /Pixel2Mesh/pixel2mesh# python demo.py --image utils/examples/
> Traceback (most recent call last):
> File "demo.py", line 3, in
> from models import GCN
> File "/Pixel2Mesh/pixel2mesh/models.py", line 3, in
> from losses import *
> File "/Pixel2Mesh/pixel2mesh/losses.py", line 2, in
> from cd_dist import *
> ImportError: dynamic module does not define init function (initcd_dist)


I also meet this problem. have you figured it out?

**Comment by JinglunYang** [comment]
I also encountered this problem, which has now been resolved.
If your cuda‘s version is not 8.0， You must recompile in the PointSetGeneration project. 
But the ’makefile‘ could not be used directly.
My revised makefile file is as follows : 

`nvcc = /usr/local/cuda-9.0/bin/nvcc
cudalib = /usr/local/cuda-9.0/lib64/
tensorflow = /usr/local/lib/python2.7/dist-packages/tensorflow/include
TF_INC=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())')

all: depthestimate/tf_nndistance_so.so depthestimate/render_balls_so.so
.PHONY : all

depthestimate/tf_nndistance_so.so: depthestimate/tf_nndistance_g.cu.o depthestimate/tf_nndistance.cpp
	g++ -std=c++11 -shared depthestimate/tf_nndistance.cpp depthestimate/tf_nndistance_g.cu.o -o depthestimate/tf_nndistance_so.so -fPIC -I $TF_INC -O2

depthestimate/tf_nndistance_g.cu.o: depthestimate/tf_nndistance_g.cu
	$(nvcc) -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11 -c -o depthestimate/tf_nndistance_g.cu.o depthestimate/tf_nndistance_g.cu -I $(tensorflow) -DGOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -O2

depthestimate/render_balls_so.so: depthestimate/render_balls_so.cpp
	g++ -std=c++11 depthestimate/render_balls_so.cpp -o depthestimate/render_balls_so.so -shared -fPIC -O2 -D_GLIBCXX_USE_CXX11_ABI=0
`
 For reference only, thanks again for sharing.

**Comment by StatML** [comment]
> I have encountered this problem before, and I have solved it now.
> If your cuda‘s version is not 8.0， You must recompile in the PointSetGeneration project.
> But the ’makefile‘ could not be used directly.
> My revised makefile file is as follows :
> 
> ```
> cudalib = /usr/local/cuda-9.0/lib64/
> tensorflow = /usr/local/lib/python2.7/dist-packages/tensorflow/include
> TF_INC=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())')
> 
> all: depthestimate/tf_nndistance_so.so depthestimate/render_balls_so.so
> .PHONY : all
> 
> depthestimate/tf_nndistance_so.so: depthestimate/tf_nndistance_g.cu.o depthestimate/tf_nndistance.cpp
> 	g++ -std=c++11 -shared depthestimate/tf_nndistance.cpp depthestimate/tf_nndistance_g.cu.o -o depthestimate/tf_nndistance_so.so -fPIC -I $TF_INC -O2
> 
> depthestimate/tf_nndistance_g.cu.o: depthestimate/tf_nndistance_g.cu
> 	$(nvcc) -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11 -c -o depthestimate/tf_nndistance_g.cu.o depthestimate/tf_nndistance_g.cu -I $(tensorflow) -DGOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -O2
> 
> depthestimate/render_balls_so.so: depthestimate/render_balls_so.cpp
> 	g++ -std=c++11 depthestimate/render_balls_so.cpp -o depthestimate/render_balls_so.so -shared -fPIC -O2 -D_GLIBCXX_USE_CXX11_ABI=0
> ```
> For reference only, thanks again for sharing.

Hi @JinglunYang I recompiled, but encounter the following issue. Do you have any ideas? Thanks!

$ sudo python demo.py --image utils/examples/plane.png 
Traceback (most recent call last):
  File "demo.py", line 3, in <module>
    from pixel2mesh.models import GCN
  File "build/bdist.linux-x86_64/egg/pixel2mesh/models.py", line 3, in <module>
    from pixel2mesh.losses import *
  File "build/bdist.linux-x86_64/egg/pixel2mesh/losses.py", line 2, in <module>
    from pixel2mesh.cd_dist import *
  File "build/bdist.linux-x86_64/egg/pixel2mesh/cd_dist.py", line 3, in <module>
    nn_distance_module=tf.load_op_library('./cd_dist.so')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 60, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: ./cd_dist.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

**Comment by tangjilin** [comment]
@XuXianbing I met the same problem, have you solved it ? Can you help me, thanks!

**Comment by XuXianbing** [comment]
> @XuXianbing I met the same problem, have you solved it ? Can you help me, thanks!

when I change the TF1.4 to TF1.3, the problem was solved! Maybe your TF version is 1.4+, you can try TF1.3.

**Comment by tangjilin** [comment]
@XuXianbing Yes, my TF is 1.9. Do you just change the TF version? Have you recomplie the .so file in the PointSetGeneration project? Or you compile your .so file in the external folder directly? Thx！

**Comment by XuXianbing** [comment]
> @XuXianbing Yes, my TF is 1.9. Do you just change the TF version? Have you recomplie the .so file in the PointSetGeneration project? Or you compile your .so file in the external folder directly? Thx！

Yes, first you should compile the .so file in the PointSetGeneration project, rename tf_nndistance_so.so to cd_dist.so and replace original cd_dist.so. If your TF version is 1.3, you won't encounter this problem!

**Comment by tangjilin** [comment]
@XuXianbing OK， I will try， thanks

**Comment by walsvid** [comment]
If there is no further discussion, I will temporarily close this issue, and if there is any problem, please feel free to open again.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
