### ISSUE TITLE
solved

### ISSUE THREAD

**Issue by AmyWan** [nywang16/Pixel2Mesh#14]
clone [https://github.com/fanhqme/PointSetGeneration](https://github.com/fanhqme/PointSetGeneration) and then run make, after changing the paths at the top of the makefile. Then copy the compiled library `tf_nndistance_so.so` located in `depthestimate` to `cd_dist.so`.

_Originally posted by @M4gicT0 in https://github.com/nywang16/Pixel2Mesh/issues/7#issuecomment-424793907_

**Comment by AmyWan** [comment]
hi ,it is suit for tf1.6.cuda9.0?

**Comment by M4gicT0** [comment]
Don't know, but it works with CUDA 8.

**Comment by XuXianbing** [comment]
> hi ,it is suit for tf1.6.cuda9.0?

No, it works with tf1.3. If you use tf1.4+,you will meet problems such as "cd_dist.so".

**Comment by M4gicT0** [comment]
@AmyWan you need to close the issue to mark it as solved

**Comment by AmrMoataz** [comment]
i am working on windows and trying to solve this error for days and nothing working!!!!!! Please help

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
