### ISSUE TITLE
How to get the GroundTruth points

### ISSUE THREAD

**Issue by ransun1004** [nywang16/Pixel2Mesh#16]
Hi, I want to know how to get the sampled GroundTruth points cloud  (with vertex normal) from the shapenet dataset.

**Comment by ransun1004** [comment]
Also, I found that the quantity of each Ground Truth point cloud sample that from the same 3D CAD sample, but the point clouds coordinates are different, it's so weird.

**Comment by ransun1004** [comment]
@tangjilin First, I haven't solved the problem. Second, if you just want to get the rendering images and ground point cloud, you can save the two parameters separately.

**Comment by tangjilin** [comment]
@ransun1004 Thanks for your reply. Given the 3D model in the shapenet dataset(.obj files), can I get the groundtruth point  cloud with normal vector to train my own model? If I can, can you share me some way to achieve it? I am not familiar with it indeed. Thanks very much!

**Comment by ransun1004** [comment]
@tangjilin The writer haven't reply  me how to get the groundtruth point cloud, sorry, if you want to train your own model, I think you could contact to the writer directly, or you can just use the dataset that the paper writer provided.

**Comment by nywang16** [comment]
@jcjohnson @ransun1004 @tangjilin 
A sample code is here:
https://github.com/nywang16/Pixel2Mesh/tree/master/data_generation

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
