### ISSUE TITLE
Train time problem

### ISSUE THREAD

**Issue by shliang0603** [nywang16/Pixel2Mesh#17]
I have trained the model.It is training the 1 epoch, but I used more than 12 hours. I have two nvidia 1080Ti gpu.How can I speed up my training and how long will the training last?

**Comment by nywang16** [comment]
@shliang0603 you can sample the training data. 3D-R2N2 render 24 views for each model, you can use 4 of them.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
