### ISSUE TITLE
cd_dist.so source?

### ISSUE THREAD

**Issue by justanhduc** [nywang16/Pixel2Mesh#18]
Thanks for opensourcing the code. I would like to request the source code for cd_dist.so so I can compile and use on Windows. If possible please provide the source. 
Thank you.

**Comment by nywang16** [comment]
@justanhduc see pixel2mesh/external folder

**Comment by justanhduc** [comment]
@nywang16 thanks very much. I have a question. Have you tried compiling it on Windows? I got so many conflicts between g++ and system files. Basically g++ specifies #pragma pack as error. Do you have any idea?

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid

**Comment by justanhduc** [comment]
hey @zshyang. just download and unzip the `.001` file. any unzip program should take care of the rest.

**Comment by zshyang** [comment]
Hi justanhduc,
I tried `unzip` command but it did not work. Could you show me your way of doing it?

**Comment by justanhduc** [comment]
Have you tried 7zip?

**Comment by zshyang** [comment]
Do you mean 7z at Linux?

**Comment by justanhduc** [comment]
Yes

**Comment by zshyang** [comment]
![Screenshot from 2020-09-19 12-26-33](https://user-images.githubusercontent.com/57812785/93687583-86ebba00-fa73-11ea-9672-dfc028a63d6e.png)
I tried. But it did not work.

**Comment by justanhduc** [comment]
you should start from .001
```7z x ShapeNetP2M.7z.001```

**Comment by langyakun** [comment]
> @nywang16 thanks very much. I have a question. Have you tried compiling it on Windows? I got so many conflicts between g++ and system files. Basically g++ specifies #pragma pack as error. Do you have any idea?

hi, have you solved this problem? i also want to use the code on windows.
