### ISSUE TITLE
About external/makefile

### ISSUE THREAD

**Issue by QianyiWu** [nywang16/Pixel2Mesh#19]
Hi, Nanyang.
Thank you for sharing the code of this excellent work. But I got some errors while using the makefile in external directory. A similar error like <a href="https://github.com/tensorflow/tensorflow/issues/12847">error</a>.

But when I remove -O2 option in nvcc command, it works. Hope it can benefit someone else.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
