### ISSUE TITLE
import error when importing cd_dist.so.

### ISSUE THREAD

**Issue by HaiyongJiang** [nywang16/Pixel2Mesh#2]
Hi @nywang16,  I encountered an error "dynamic module does not define init function (initcd_dist)" when importing the library. Can you kindly share or release the source code for cd_dist? Thank you very much.

**Comment by nywang16** [comment]
@HaiyongJiang One solution is swiching your tensorflow to version 1.3 if you want to used our code directly.
Another solution is to build cd_dist yourself, please refer to https://github.com/fanhqme/PointSetGeneration

**Comment by anandbhattad** [comment]
My tensorflow version is 1.3. But I do get the same error.

**Comment by HaiyongJiang** [comment]
@nywang16, Thank you. I am using tensorflow 1.3, but it did not work. I will try to compile from source.

**Comment by walsvid** [comment]
@HaiyongJiang @anandbhattad You can reference this tutorial for build new op in TensorFlow: [ref1](https://www.tensorflow.org/extend/adding_an_op#gpu_support), or you can reference my gist for build so file: [ref2](https://gist.github.com/walsvid/960d54d350182c8524947e201d0da101), you can change the path of CUDA and so file name to your settings. 

Or according to the nanyang's solution, refer to the url of the repo he gave, recompile from the source code

**Comment by jaymefosa** [comment]
@walsvid Thanks for the gist, I've been trying to use it combined with the original source at PU-net 

https://github.com/yulequan/PU-Net/tree/master/code/tf_ops/CD

Here is the modified file, based on your gist + their makefile. But I'm getting an error: 
```
make: Circular tf_nndistance_g.cu <- tf_nndistance_g.cu.o dependency dropped.
make: Nothing to be done for 'all'.
```

Would you be able to tell me what should be modified?

```

TF_CFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_compile_flags()))') )
TF_LFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_link_flags()))') )
CUDA_LIB=/usr/local/cuda-9.0/lib64/

all: tf_nndistance_so.so

# tf.__version__ >= 1.4 link libtensorflow_framework.so
tf_nndistance_so.so: tf_nndistance_g.cu.o tf_nndistance.cpp
	g++ -std=c++11 tf_nndistance.cpp tf_nndistance_g.cu.o -o tf_nndistance_so.so -shared -fPIC -I ${TF_ROOT}/include -I ${CUDA_ROOT}/include -I ${TF_ROOT}/include/external/nsync/public -lcudart -L ${CUDA_ROOT}/lib64/ -L ${TF_ROOT} -ltensorflow_framework -O2

tf_nndistance_g.cu.o: tf_nndistance_g.cu
	nvcc -std=c++11 -c -o  tf_nndistance_g.cu.o tf_nndistance_g.cu ${TF_CFLAGS[@]} -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -O2
```

**Comment by jaymefosa** [comment]
@walsvid After just running the makefile that you provided with the CUDA path changed I'm getting a 'file not found' error for a tensorflow file:

tf_nndistance.cpp:1:42: fatal error: tensorflow/core/framework/op.h: No such file or directory

Is there some kind of include issue?

**Comment by jaymefosa** [comment]
@HaiyongJiang What did you rename the file to?

**Comment by HaiyongJiang** [comment]
You can rename it to whatever you want, except cd_dist.so.  Line#3 also should be changed accordingly.

**Comment by AmyWan** [comment]
could you help me recompile dict.so?@HaiyongJiang

**Comment by HaiyongJiang** [comment]
I think the problem is not in the cd_dist.so.  You need to rename cd_dist.so to another name, and then change the importing command in cd_dist.py accordingly. Hope it helps.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
