### ISSUE TITLE
quesions about F-score and CD/EMD

### ISSUE THREAD

**Issue by xiaomingjie** [nywang16/Pixel2Mesh#20]
HI @nywang16 
It seems you didn't explain how you got F-score of your method or other approach. And I couldn't figure out where and how your CD/EMD and others come from. I suppose that there should be a normalization explanation, e.g., the whole point cloud of a model are in a semi-sphere where r = 1..
So could you tell more about your F-score and CD/EMD?

**Comment by nywang16** [comment]
@xiaomingjie See details in eval_testset.py

**Comment by xiaomingjie** [comment]
Thanks a lot. But I still have a confusion about the normalization of your sampled points and predicted points since different normalization causes different CD/EMD..

**Comment by walsvid** [comment]
Pixel2Mesh only calculate ground truth points coordinate for CD/EMD.  Points normal use for smooth surface.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
