### ISSUE TITLE
Earth Mover distance?

### ISSUE THREAD

**Issue by jcjohnson** [nywang16/Pixel2Mesh#21]
Table 2 in your paper reports both Chamfer distance and Earth-Mover distances; however I can't find your code for computing EMD. Can you share it?

**Comment by nywang16** [comment]
Really sorry for late reply. The CD and EMD code is here:
https://github.com/nywang16/Pixel2Mesh/tree/master/pixel2mesh/external

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
