### ISSUE TITLE
InvalidArgumentError: flat indices[117, :] = [2, 7] does not index into param (shape: [7,7,512]).

### ISSUE THREAD

**Issue by tangjilin** [nywang16/Pixel2Mesh#22]
When I run "python demo.py --image utils/examples/plane.png" , I meet the problem:

InvalidArgumentError (see above for traceback): flat indices[117, :] = [2, 7] does not index into param (shape: [7,7,512]).
 [[Node: graphprojection_1/GatherNd_13 = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](gcn/Squeeze_3, graphprojection_1/stack_13)]]

However, I didn't change anything. 
My TF is 1.9 and Cuda is 9.0 , I compile my own cd_dist.so. I didn't know what is wrong. Can anyone help me ?  Thanks very much!

**Comment by jspih** [comment]
I also have this issue, but on tensorflow 1.3 and cuda 10.0.

**Comment by jspih** [comment]
I even installed cuda version 8.0, is there a specific numpy version that was used? Or any other versions?

**Comment by tangjilin** [comment]
@jspih Thanks very much！ I will try!

**Comment by tangjilin** [comment]
GPU version doesn‘t have any problem. However, CPU should modify x2 and y2.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
