### ISSUE TITLE
hi .would you like to share me with how to generate the info_eplised.dat?

### ISSUE THREAD

**Issue by AmyWan** [nywang16/Pixel2Mesh#24]
how to produce my info_ellipsoid.dat?how i use my face1 to generate the .dat?

**Comment by gopikrishnachaganti** [comment]
@walsvid can you please be more specific what all information went in dat file creation, i could not find specifically over in data generation & utls.py. appreciate your support.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
