### ISSUE TITLE
can not download the pre-train model.

### ISSUE THREAD

**Issue by FeiHsiang** [nywang16/Pixel2Mesh#26]
Hi, 
first appreciating for this great work.
When I try to download the pre-train model through the link,
 (http://bigvid.fudan.edu.cn/pixel2mesh/eccv2018/checkpoint.zip)
the website must need to log-in to Fudan University account, unfortunately I can't. 

May I get the model from other free-space?
 
Thanks a lot!

**Comment by nywang16** [comment]
@FeiHsiang 

https://drive.google.com/file/d/1dJLuHDkhEiFQIClbDw6_qDyyWWe9pGWT/view?usp=sharing

**Comment by FeiHsiang** [comment]
@nywang16 
Thanks a lot for your quick reply! 
I will try to use it as soon as I can.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
