### ISSUE TITLE
About info_ellipsoid.dat

### ISSUE THREAD

**Issue by wenbinTse** [nywang16/Pixel2Mesh#28]
Could anyone tell me what's `info_ellipsoid.dat` for and how to open `face.obj`(Meshlab cannot open it). Thx.

**Comment by nywang16** [comment]
@wenbinTse info_ellipsoid.dat contains the basic information about the initial mesh,e.g. topology, initial 3d position.

**Comment by KnightOfTheMoonlight** [comment]
could u share your initial ellipsoid obj file?

**Comment by luotuoqingshan** [comment]
@KnightOfTheMoonlight  It's in Data.

**Comment by KnightOfTheMoonlight** [comment]
@luotuoqingshan Thanks! I found it.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
