### ISSUE TITLE
About the version of ShapeNet

### ISSUE THREAD

**Issue by tangjilin** [nywang16/Pixel2Mesh#29]
Hi!

For 3D  model, there is ShapeNetCore v1 , ShapeNetCore v2 and ShapeNetSem in the website of ShapeNet. I download the ShapeNetCore v2 for the 3D model. However, I find it may be different from the 3D model from your model(I compare the corresponding model.obj in https://github.com/nywang16/Pixel2Mesh/tree/master/data_generation and ShapeNetCore v2 ).

I wonder which version is your shapenet 3D model which matches with the rendering image in 3D-R2N2. 
Can someone help me? Thanks very much!

**Comment by walsvid** [comment]
Hi! We using ShapeNetCore **v1** data.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
