### ISSUE TITLE
Speed of Each Iteration

### ISSUE THREAD

**Issue by lijiaman** [nywang16/Pixel2Mesh#3]
Hi,
Thanks for releasing codes! I wonder how much time each iteration cost in your machine. I tested the codes in Titan V, it's about 0.13s for each iteration. This seems cannot finish 50 epochs within 72 hours.

**Comment by nywang16** [comment]
@lijiaman In our paper, we used 70,000 images as our training data for time reason, i.e. we take a subset of render views provided  by 3D-R2N2, where they render 24 views for each model, we used 2 of them.

**Comment by lijiaman** [comment]
I see. Thanks for your reply!

**Comment by anandbhattad** [comment]
Hi @lijiaman , how did you resolve #2?

**Comment by lijiaman** [comment]
I tried several times, also met the issue in #2, but don't remember exactly what fixed it. I think keeping exactly the same environment can work, I installed tf1.3, py2.7, tf layer, and also installed cuda8.0, cudnn6, (my workstation used newer version and throws some errors)then follow their README, do setup.py first, and it should work now without compiling from source (also tried compiling from source, but it seems still some issues about version.. so keeping the same env is important).

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
