### ISSUE TITLE
About the projection layer

### ISSUE THREAD

**Issue by blister1824** [nywang16/Pixel2Mesh#30]
I think in the projection layer, the discrete operation rasterization is not differentiable, so BP is prevented and i wonder know how to update the variables in the image convolution layer?

**Comment by wenbinTse** [comment]
I don't think it includes trainable variables, so it should work.

**Comment by longbowzhang** [comment]
Hi @walsvid @blister1824
The above link for the Supplementary Materials is broken down.
Could any of you share the suppl file with me?

Many thanks in advance.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
