### ISSUE TITLE
How to calculate edge weights in adj supports?

### ISSUE THREAD

**Issue by Peng154** [nywang16/Pixel2Mesh#33]
i saw the number of supports is 2 in file "train.py" :

`num_supports = 2`

I am curious about the problem why there ser two adj supports for one ellipsoid graph.

**Comment by Peng154** [comment]
Now i know the first adj support is a diagonal matrix, and the edge weights are all 1.0, and the second adj supprt is a matrix that displays adjacency of different nodes, but i still don't know how to calculate the weight between two neighbour-node.
Anyone Help? Thanks.

**Comment by walsvid** [comment]
To calculate `supports`, you can reference to [this code](https://github.com/tkipf/gcn/blob/master/gcn/utils.py#L149), we calculate the `supports` using `chebyshev_polynomials`. For more detail about graph CNN, you can reference to original paper [Semi-Supervised Classification with Graph Convolutional Networks](http://arxiv.org/abs/1609.02907)

**Comment by walsvid** [comment]
If you have solved your problem, please close the issue.

**Comment by KnightOfTheMoonlight** [comment]
So basically, you are using a sparse matrix representation for support (namely, the symmetrical normalized adjacency matrix)?

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
