### ISSUE TITLE
NotFoundError: ./external/tf_nndistance_so.so: undefined symbol: 

### ISSUE THREAD

**Issue by rubilin** [nywang16/Pixel2Mesh#34]
My specs: Ubuntu16.04 ,Tensorflow 1.12，opencv3.4.0

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
