### ISSUE TITLE
generate_data.py DOES NOT work for other meshes.

### ISSUE THREAD

**Issue by WangZixuan** [nywang16/Pixel2Mesh#36]
I tested code of generate_data.py, but it only works for 1a0bc9ab92c915167ae33d942430658c, but does not work for other meshes. To be more specific, I use other rendering_metadata.txt of the meshes but the result is quit weird: the projection does not match the original rendering images from ShapeNetRendering of 3D-R2N2.
Is it because you hardcode some parameters in the code? , or did I test wrongly?
Please have a check, thank you.

**Comment by WangZixuan** [comment]
P.S. I test on meshes of 02598343(car) from ShapeNetCore.v2 and the rendering metadata and images from ShapeNetRendering of 3DR2N2.

**Comment by WangZixuan** [comment]
I find the difference between the mesh provided and the mesh from ShapeNetCore.v2, that's where the problem lies.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid

**Comment by WangZixuan** [comment]
Download all the 7z files and unzip tools(like winrar, 7z) will automatically unzip all

**Comment by zshyang** [comment]
Hi WangZixuan,
Thanks for your reply. Do you use the unzip tool on Windows or Linux?

**Comment by WangZixuan** [comment]
If you are using Linux, please search in Google for unzipping

**Comment by zshyang** [comment]
It is not working. I do not know why
![Screenshot from 2020-09-19 12-26-33](https://user-images.githubusercontent.com/57812785/93687781-2bbac700-fa75-11ea-9050-66574a65f3cc.png)
