### ISSUE TITLE
About face order in .obj

### ISSUE THREAD

**Issue by lijiaman** [nywang16/Pixel2Mesh#4]
Hi, 
1. It seems the face order in your initial mesh (after splitting edge) is not consistent? (this mesh is generated by using data from .dat file and face2.obj) some parts are black, some parts are white. and in the plane.obj generated by demo, it also looks like this. Is there a reason that not using consistent order? I assume the face order doesn't matter? 
2. The triangles in initial mesh look not evenly distributed, is this better than even?
![init_mesh](https://user-images.githubusercontent.com/12640532/44810200-ff3a6680-ab9e-11e8-9f96-5d82f61d475a.png)

**Comment by nywang16** [comment]
@lijiaman  Hi, sorry for late reply, I got distracted these days for my graduation and some other thing.
1. Face order doesn't matter, I made some mistake when generating face2.obj, the face vertex order is wrong. Let me know if you fixed this problem.
2. Doesn't matter, our method is not sensitive to the initial shape.

**Comment by lijiaman** [comment]
Hi Nanyang, thanks for the reply. I have trained with my codes using your .dat file and my initial mesh(consistent order, counter-clockwise), the shape of results look good, but the visualization are all black in meshlab (which means faces are flipped during training). I wonder how you did the data preprocessing. Did you use clockwise order(.obj) to calculate the normal when do data preprocessing? And I also checked the number of vertices of official ShaopeNet data and the data you provided, it seems different, could you explain a bit about how you did the data preprocessing? Thanks a lot!

**Comment by chientran95** [comment]
@lijiaman Hi, can you tell me which data in .dat file you used to create above mesh ?

**Comment by walsvid** [comment]
Hi @chientran95, we have recently update code for generate .dat file. And it also contains code to generate corresponding obj mesh, please check https://github.com/nywang16/Pixel2Mesh/blob/master/GenerateData/4_make_auxiliary_dat_file.ipynb for more details.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
