### ISSUE TITLE
the dataset can not download !

### ISSUE THREAD

**Issue by liyouhua123** [nywang16/Pixel2Mesh#41]
sorry, I can not finish the downloading of the training dataset !  and I find that it is defferent from the shapenet dataset on https://www.shapenet.org/ ! Does anyone meet this problem? I want to how to convert right data！

**Comment by gopikrishnachaganti** [comment]
All the dataset was converted to .dat format using point clouds, normal & camera intrinsics data generated from Shapenet dataset. Not sure how the .dat file has been created for dataset to train.

**Comment by liyouhua123** [comment]
Thank you very much ! The problem was solved ! Hope you are well!




------------------ 原始邮件 ------------------
发件人: "gopikrishnachaganti"<notifications@github.com>;
发送时间: 2019年4月26日(星期五) 晚上8:30
收件人: "nywang16/Pixel2Mesh"<Pixel2Mesh@noreply.github.com>;
抄送: "李大爷与抱怨小孩"<1515084675@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [nywang16/Pixel2Mesh] the dataset can not download ! (#41)




All the dataset was converted to .dat format using point clouds, normal & camera intrinsics data generated from Shapenet dataset. Not sure how the .dat file has been created for dataset to train.

**Comment by gopikrishnachaganti** [comment]
Can you tell me how you generated the dat format for your own dataset?

**Comment by walsvid** [comment]
We have released the code for the dataset, please refer to `GenerateData`. If there are no further questions, I will temporarily close the issue.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it?

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
