### ISSUE TITLE
No Suitable Image Found Error

### ISSUE THREAD

**Issue by Colton-Bishop** [nywang16/Pixel2Mesh#46]
When attempting to run the demo, I receive an error that tf_nndistance_so.so is an unknown file type, an no suitable image can be found. The full error is shown below.

(testEnv) $ python demo.py --image utils/examples/plane.png
Traceback (most recent call last):
  File "demo.py", line 3, in <module>
    from pixel2mesh.models import GCN
  ...
packages/tensorflow/python/framework/load_library.py", line 60, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(./external/tf_nndistance_so.so, 6): no suitable image found.  Did find:
	./external/tf_nndistance_so.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/Bishop/Desktop/Testing/Pixel2Mesh/pixel2mesh/external/tf_nndistance_so.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00

I'm not sure if the issue is one of compatibility. The specs of my gcc are:

(testEnv) $ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

Does anyone have any ideas on how to resolve this?

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
