### ISSUE TITLE
About the generation process of the mesh

### ISSUE THREAD

**Issue by tangjilin** [nywang16/Pixel2Mesh#48]
In my opinion， in the training stage,  you only aim to learn the point cloud (represented by vertex，output3 in code) .  Finally, you get the mesh by: np.vstack((vert, face)).

Thus, can you tell the difference between point clouds and vertex of mesh here? What' more, can you tell me the meaning of face.obj files and how to generate it?

Thanks!

**Comment by Astonecutter** [comment]
I  also confuse about that.Do you solve it?

**Comment by tangjilin** [comment]
Given the point cloud and face.obj, we can generate the final mesh.

**Comment by Astonecutter** [comment]
THX~

**Comment by walsvid** [comment]
Hi, @Astonecutter @tangjilin 

Our 3D mesh representation and point cloud are significantly different. Specifically, 1. We use graph convolution. It takes into account the relationship of the edges in the calculation. 2. The loss we calculate are different, whether it is edge loss or laplacian loss or norm loss, needs to consider the connection of the edges.

In general, although the edges of the training phase are not explicitly visible, there is a edge relationship between our mesh vertices to ensure the advantages of mesh representation. This is the significant difference between us and the point cloud representation.

**Comment by zhiwenfan** [comment]
> Hi, @Astonecutter @tangjilin
> 
> Our 3D mesh representation and point cloud are significantly different. Specifically, 1. We use graph convolution. It takes into account the relationship of the edges in the calculation. 2. The loss we calculate are different, whether it is edge loss or laplacian loss or norm loss, needs to consider the connection of the edges.
> 
> In general, although the edges of the training phase are not explicitly visible, there is a edge relationship between our mesh vertices to ensure the advantages of mesh representation. This is the significant difference between us and the point cloud representation.

Hi, Chao Wen,
Do you mean that during training stage, different vertex  contain connection relationship defined by edges? And the edges  between different vertex is unchanged during the training stage. 
Besides, is the  edges defined by ellipsoid.edges which is loaded from 'info_ellipsoid.dat' ?

**Comment by walsvid** [comment]
@zhiwenfan Yes, the edge of mesh is defined by the adjacency relationship of graph and those  connection relationship are unchanged. Yes, the initial edges are defined by ellipsoid.edges.

**Comment by zhiwenfan** [comment]
> @zhiwenfan Yes, the edge of mesh is defined by the adjacency relationship of graph and those connection relationship are unchanged. Yes, the initial edges are defined by ellipsoid.edges.

Thanks

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
