### ISSUE TITLE
Docker image for Pixel2Mesh

### ISSUE THREAD

**Issue by gopikrishnachaganti** [nywang16/Pixel2Mesh#49]
Hi, looks very promising after reading your publication on building 3d model using single RGB image.  i would like to try the algorithm and see if i can use it. Can you provide a docker image with Ubuntu OS which will make the things easier as so many dependencies are required while installing including right versions. i could see some of the limitations like OS version, CUDA, cudnn, Tensorflow versions etc. appreciate the work you guys have done.  

Thanks,
Gopikrishna

**Comment by gopikrishnachaganti** [comment]
@nywang16 the new code ran without any issues on my below environment:
Ubuntu 18.04, CUDA 9.2, python 2.7, nvidia-390. 

Thanks. i tried with some images i do have like chair/table images etc, the output is weird. closing this issue and will raise another one for that.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
