### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [256] rhs shape= [192]

### ISSUE THREAD

**Issue by zjq630174388** [nywang16/Pixel2Mesh#50]
when I make the code and install the new code, there are some problems

**Comment by zjq630174388** [comment]
ok I didn't undapte all the new file in the project even the checkpoint is different~

**Comment by Weipeilang** [comment]
Hello,I meet the same issue.I want to know how to solve it,and I can`t understand what you say

**Comment by zjq630174388** [comment]
I am sorry that I have forgot that how to slove it.
Maybe the checkpoint is different so you need to install the right checkpoint for the model.




------------------ 原始邮件 ------------------
发件人: "If you,if I"<notifications@github.com>;
发送时间: 2019年5月5日(星期天) 下午4:38
收件人: "nywang16/Pixel2Mesh"<Pixel2Mesh@noreply.github.com>;
抄送: "囧┢┦aΡｐy"<630174388@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [nywang16/Pixel2Mesh]tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requiresshapes of both tensors to match. lhs shape= [256] rhs shape= [192] (#50)




Hello,I meet the same issue.I want to know how to solve it,and I can`t understand what you say

**Comment by Weipeilang** [comment]
I download the checkpoint on https://drive.google.com/file/d/1gD-dk-XrAa5mfrgdZSunjaS6pUUWsZgU/view?usp=sharing and unzip it into /Data.However,it doesn`t work




------------------ 原始邮件 ------------------
发件人: "Ball"<notifications@github.com>;
发送时间: 2019年5月5日(星期天) 下午4:52
收件人: "nywang16/Pixel2Mesh"<Pixel2Mesh@noreply.github.com>;
抄送: "If you,if I"<2546954766@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [nywang16/Pixel2Mesh]tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requiresshapes of both tensors to match. lhs shape= [256] rhs shape= [192] (#50)



I am sorry that I have forgot that how to slove it. 
 Maybe the checkpoint is different so you need to install the right checkpoint for the model. 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "If you,if I"<notifications@github.com>; 
 发送时间: 2019年5月5日(星期天) 下午4:38 
 收件人: "nywang16/Pixel2Mesh"<Pixel2Mesh@noreply.github.com>; 
 抄送: "囧┢┦aΡｐy"<630174388@qq.com>; "State change"<state_change@noreply.github.com>;  
 主题: Re: [nywang16/Pixel2Mesh]tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requiresshapes of both tensors to match. lhs shape= [256] rhs shape= [192] (#50) 
 
 
 
 
 Hello,I meet the same issue.I want to know how to solve it,and I can`t understand what you say

**Comment by zjq630174388** [comment]
Sorry, If it can't work then I don't know how to slove it.




------------------ 原始邮件 ------------------
发件人: "If you,if I"<notifications@github.com>;
发送时间: 2019年5月5日(星期天) 下午4:57
收件人: "nywang16/Pixel2Mesh"<Pixel2Mesh@noreply.github.com>;
抄送: "囧┢┦aΡｐy"<630174388@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [nywang16/Pixel2Mesh]tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requiresshapes of both tensors to match. lhs shape= [256] rhs shape= [192] (#50)



I download the checkpoint on https://drive.google.com/file/d/1gD-dk-XrAa5mfrgdZSunjaS6pUUWsZgU/view?usp=sharing and unzip it into /Data.However,it doesn`t work 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "Ball"<notifications@github.com>; 
 发送时间: 2019年5月5日(星期天) 下午4:52 
 收件人: "nywang16/Pixel2Mesh"<Pixel2Mesh@noreply.github.com>; 
 抄送: "If you,if I"<2546954766@qq.com>; "Comment"<comment@noreply.github.com>;  
 主题: Re: [nywang16/Pixel2Mesh]tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requiresshapes of both tensors to match. lhs shape= [256] rhs shape= [192] (#50) 
 
 
 
 I am sorry that I have forgot that how to slove it.  
  Maybe the checkpoint is different so you need to install the right checkpoint for the model.  
   
   
   
   
  ------------------ 原始邮件 ------------------  
  发件人: "If you,if I"<notifications@github.com>;  
  发送时间: 2019年5月5日(星期天) 下午4:38  
  收件人: "nywang16/Pixel2Mesh"<Pixel2Mesh@noreply.github.com>;  
  抄送: "囧┢┦aΡｐy"<630174388@qq.com>; "State change"<state_change@noreply.github.com>;   
  主题: Re: [nywang16/Pixel2Mesh]tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requiresshapes of both tensors to match. lhs shape= [256] rhs shape= [192] (#50)  
   
   
   
   
  Hello,I meet the same issue.I want to know how to solve it,and I can`t understand what you say

**Comment by KnightOfTheMoonlight** [comment]
this is due to `eval_testset.py` file setting.
```
flags.DEFINE_integer('hidden', 192, 'Number of units in  hidden layer.')
flags.DEFINE_integer('hidden', 256, 'Number of units in  hidden layer.')
```

**Comment by wanqunAmy** [comment]
I 

> 这是由于`eval_testset.py`文件设置。
> 
> ```
> flags.DEFINE_integer('hidden', 192, 'Number of units in  hidden layer.')
> ```
> 
> ->
> 
> ```
> flags.DEFINE_integer('hidden', 256, 'Number of units in  hidden layer.')
> ```

I try this ,but did not work? How?thank you

**Comment by fashionguy** [comment]
@wanqunAmy Have you sovled the problem? I have the same one.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid

**Comment by fashionguy** [comment]
Hello,
if you can open the link, you just download the dataset which includes five files.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nywang16/Pixel2Mesh"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月16日(星期三) 凌晨4:26
收件人:&nbsp;"nywang16/Pixel2Mesh"<Pixel2Mesh@noreply.github.com&gt;;
抄送:&nbsp;"Stan"<3301225509@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [nywang16/Pixel2Mesh] tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [256] rhs shape= [192] (#50)





 
Hi,
 Do you know how to download the dataset and unzip it from the link below?
 https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid

**Comment by zshyang** [comment]
Hi,
Thanks a lot for your reply. 
Do you mean that once I download all the five files then they will combine automatically?

**Comment by fashionguy** [comment]
Dataset includes the four files. In other words, these four files are a whole. After the download is complete, just unzip the first file .001. This is a large file compression, you search it, easy to unzip.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nywang16/Pixel2Mesh"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月16日(星期三) 下午3:33
收件人:&nbsp;"nywang16/Pixel2Mesh"<Pixel2Mesh@noreply.github.com&gt;;
抄送:&nbsp;"Stan"<3301225509@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [nywang16/Pixel2Mesh] tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [256] rhs shape= [192] (#50)





 
Hi,
 Thanks a lot for your reply.
 Do you mean that once I download all the five files then they will combine automatically?

**Comment by zshyang** [comment]
Thanks a lot for your reply.
Do you mean I could unzip the files following the following steps?
https://stackoverflow.com/questions/31481701/how-to-extract-files-from-a-large-30gb-zip-file-on-linux-server
Or do you mean to share the command line you have used?

**Comment by fashionguy** [comment]
You are welcome.
unzip ***.001


You try this command.
I remember it is very easy. It's been too long, a bit forgotten.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nywang16/Pixel2Mesh"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月16日(星期三) 下午3:42
收件人:&nbsp;"nywang16/Pixel2Mesh"<Pixel2Mesh@noreply.github.com&gt;;
抄送:&nbsp;"Stan"<3301225509@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [nywang16/Pixel2Mesh] tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [256] rhs shape= [192] (#50)





 
Thanks a lot for your reply.
 Do you mean I could unzip the files following the following steps?
 https://stackoverflow.com/questions/31481701/how-to-extract-files-from-a-large-30gb-zip-file-on-linux-server
 Or do you mind to share the command line you have used?

**Comment by zshyang** [comment]
I tried the command ` unzip ShapeNetP2M.7z.001`.
But It gives me the following error.
```
Archive:  ShapeNetP2M.7z.001
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ShapeNetP2M.7z.001 or
        ShapeNetP2M.7z.001.zip, and cannot find ShapeNetP2M.7z.001.ZIP, period.
```

**Comment by fashionguy** [comment]
Sorry to see the email late.
7z x file.7z.001
The extension is 7z, so&nbsp;try this.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nywang16/Pixel2Mesh"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月17日(星期四) 凌晨2:11
收件人:&nbsp;"nywang16/Pixel2Mesh"<Pixel2Mesh@noreply.github.com&gt;;
抄送:&nbsp;"Stan"<3301225509@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [nywang16/Pixel2Mesh] tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [256] rhs shape= [192] (#50)





 
I tried the command  unzip ShapeNetP2M.7z.001.
 But It gives me the following error.
 Archive:  ShapeNetP2M.7z.001   End-of-central-directory signature not found.  Either this file is not   a zipfile, or it constitutes one disk of a multi-part archive.  In the   latter case the central directory and zipfile comment will be found on   the last disk(s) of this archive. unzip:  cannot find zipfile directory in one of ShapeNetP2M.7z.001 or         ShapeNetP2M.7z.001.zip, and cannot find ShapeNetP2M.7z.001.ZIP, period.

**Comment by zshyang** [comment]
Thanks a lot! I tried. But it did not work.
![Screenshot from 2020-09-19 12-26-33](https://user-images.githubusercontent.com/57812785/93687747-e1394a80-fa74-11ea-933e-6b6d04e14a4f.png)
