### ISSUE TITLE
Some problems about sample_points

### ISSUE THREAD

**Issue by zjq630174388** [nywang16/Pixel2Mesh#51]
when I apply upsample.mlx to the model.obj on meshlab, the meshlab close unspectly

**Comment by zjq630174388** [comment]
May the version have some problems

**Comment by zjq630174388** [comment]
Change the format of upsample file and it will work

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
