### ISSUE TITLE
How to create my own data set?

### ISSUE THREAD

**Issue by gopikrishnachaganti** [nywang16/Pixel2Mesh#55]

**Comment by gopikrishnachaganti** [comment]
Can anybody help? anybody generated their own dataset?

**Comment by gopikrishnachaganti** [comment]
i could not get how the .dat file created with point cloud and vertex normal, curios if somebody created  .dat file with point clouds, could not find even in the code how it was generated for dataset. Shapenet dataset is not directly used. Appreciate your support.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
