### ISSUE TITLE
three mesh block

### ISSUE THREAD

**Issue by tingfengwanxiao** [nywang16/Pixel2Mesh#56]
How can I output the shape of the first block and second block in the demo?I want to observe the process.thanks

**Comment by walsvid** [comment]
Hi @tingfengwanxiao , you can let `sess.run` output `model.out1` and `model.out2`. These are the meshes of the previous stages.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
