### ISSUE TITLE
how to compile cd_dist.so

### ISSUE THREAD

**Issue by jiangxiluning** [nywang16/Pixel2Mesh#6]
hello, I want to run the demo on mac os. I need to compile the cd_dist.so by myself, but the link you post did not tell any information about it. Please help me, thx.

**Comment by nywang16** [comment]
@jiangxiluning please refer to https://github.com/fanhqme/PointSetGeneration

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
