### ISSUE TITLE
data

### ISSUE THREAD

**Issue by xiayizhan2017** [nywang16/Pixel2Mesh#62]
hi，
I want to know the theory of converting cloud data into two-dimensional images.
Thanks in advance!

**Comment by walsvid** [comment]
Hi @xiayizhan2017, you can refer to the pinhole camera model in 3D vision, which is described in detail.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
