### ISSUE TITLE
Hello，why not use vgg19 or resnet instead vgg16 to extract image features？

### ISSUE THREAD

**Issue by 1003581** [nywang16/Pixel2Mesh#68]

**Comment by walsvid** [comment]
Hi, as I have explain in walsvid/Pixel2MeshPlusPlus#1. More complex encoder structures are possible, and our work is more focused on the generation part, so there is no deliberate choice for the encoder.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
