### ISSUE TITLE
cPickle

### ISSUE THREAD

**Issue by shersoni610** [nywang16/Pixel2Mesh#69]
Hello,

It seems Anaconda does not have cPickle. How to make the code work?

ModuleNotFoundError: No module named 'cPickle'

**Comment by walsvid** [comment]
Hi, cPickle is standard libraries for python2, you can directly use it without install any external packages.

**Comment by shersoni610** [comment]
It seems that Anaconda uses Python3.7.4 these days. Is there a way to make
it work for Python 3.7.4?

Thanks

**Comment by walsvid** [comment]
You can create a new conda virtual environment and specify the version of python.

**Comment by shersoni610** [comment]
it seems that Python 3.7+ has pickle instead of cPickle. I will try to
change Pixel2Mesh with the new function instead of using
Old python.

Thanks

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
