### ISSUE TITLE
problems about cd_dist.so

### ISSUE THREAD

**Issue by XuXianbing** [nywang16/Pixel2Mesh#7]
cd_dist.so is not specified to run on windows

**Comment by nywang16** [comment]
@XuXianbing please refer to https://github.com/fanhqme/PointSetGeneration

**Comment by XuXianbing** [comment]
I looked at this link roughly, but still have not found how to deal with cd_dist.so problems such as ".\cd_dist.so not found", can you give a more detailed solution? Thank you!

**Comment by qk8937599** [comment]
@XuXianbing you should run demo on Linux instead of Windows.I have the same problem with your when i run on windows.

**Comment by M4gicT0** [comment]
> I looked at this link roughly, but still have not found how to deal with cd_dist.so problems such as ".\cd_dist.so not found", can you give a more detailed solution? Thank you!

clone [https://github.com/fanhqme/PointSetGeneration](https://github.com/fanhqme/PointSetGeneration) and then run make, after changing the paths to the paths at the top of the makefile. Then copy the compiled library `tf_nndistance_so.so` located in `depthestimate` to `cd_dist.so`.

**Comment by XuXianbing** [comment]
> > I looked at this link roughly, but still have not found how to deal with cd_dist.so problems such as ".\cd_dist.so not found", can you give a more detailed solution? Thank you!
> 
> clone https://github.com/fanhqme/PointSetGeneration and then run make, after changing the paths at the top of the makefile. Then copy the compiled library `tf_nndistance_so.so` located in `depthestimate` to `cd_dist.so`.

after copy the compiled library tf_nndistance_so.so located in depthestimate to cd_dist.so,when I run the demo, I find these problem: "undefined symbol: _ZTIN10tensorflow8OpKernelE", This is because when compiling code with g++, it is not used by the tensorflow_framework.so dynamic library. But I don't know how to use it.

**Comment by M4gicT0** [comment]
What is not used by the tensorflow library ? Have you installed TensorFlow ?

**Comment by XuXianbing** [comment]
> What is not used by the tensorflow library ? Have you installed TensorFlow ?

After I changed TF1.4 to TF1.3, this problem was solved.

**Comment by AmyWan** [comment]
@XuXianbing @M4gicT0 
I used tf1.3,cuda8, cudnn7.but when I ran ,the error like:

 File "/home/amywan/Desktop/Pixel2Mesh-master/pixel2mesh/cd_dist.py", line 4, in <module>
    nn_distance_module=tf.load_op_library('./cd_dist.so')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)


tensorflow.python.framework.errors_impl.NotFoundError: ./cd_dist.so: cannot open shared object file: No such file or directory

**Comment by AmyWan** [comment]
@M4gicT0 hi,I have done you say ,compile and copy.it is error
Traceback (most recent call last):
  File "demo.py", line 3, in <module>
    from pixel2mesh.models import GCN
  File "/home/amywan/Desktop/Pixel2Mesh/pixel2mesh/models.py", line 3, in <module>
    from pixel2mesh.losses import *
  File "/home/amywan/Desktop/Pixel2Mesh/pixel2mesh/losses.py", line 2, in <module>
    from pixel2mesh.cd_dist import *
  File "/home/amywan/Desktop/Pixel2Mesh/pixel2mesh/cd_dist.py", line 3, in <module>
    nn_distance_module=tf.load_op_library('./dist.so')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: ./dist.so: cannot open shared object file: No such file or directory

**Comment by M4gicT0** [comment]
@AmyWan For some reason it's named differently in your import... So just change line 3 of cd_dist.py to `nn_distance_module=tf.load_op_library('./cd_dist.so')`, or just rename cd_dist.so to dist.so...

**Comment by AmyWan** [comment]
@M4gicT0 yes,I changed the name : nn_distance_module=tf.load_op_library('./dist.so'),including cd_dist.so to dist.so.I do you said.but it is error,too.

**Comment by M4gicT0** [comment]
Same error ? You need to be more specific

**Comment by AmyWan** [comment]
yes,I follow the readme and install tf1.3,cuda8,cundnn6. Download the code ,checkpoint,and run the demo.py.
I follow "clone https://github.com/fanhqme/PointSetGeneration and then run make,Then copy the compiled library tf_nndistance_so.so located in depthestimate to cd_dist.so."I use this cd_dist.so to replace old one,and also rename .it has error too.

**Comment by AmyWan** [comment]
@M4gicT0 
yes,I follow the readme and install tf1.3,cuda8,cundnn6. Download the code ,checkpoint,and run the demo.py.
I follow "clone https://github.com/fanhqme/PointSetGeneration and then run make,Then copy the compiled library tf_nndistance_so.so located in depthestimate to cd_dist.so."I use this cd_dist.so to replace old one,and also rename .it has error too.

**Comment by sonej** [comment]
.

**Comment by AmyWan** [comment]
thank you @M4gicT0 I have solved .

**Comment by M4gicT0** [comment]
@XuXianbing please close the issue if it is solved :wink:

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
