### ISSUE TITLE
the issues of faces for ellipsoid in train.py and 4_make_auxiliary_dat_file.ipynb

### ISSUE THREAD

**Issue by caixialiu-bjut** [nywang16/Pixel2Mesh#72]
It is found that faces are different by train.py and 4_make_auxiliary_dat_file.ipynb
In train.py, faces:
('feed_dict(faces)[0]:', (462, 4), array([[  0,   1,   2,   7],
       [  0,   2,   1,  33],
       [  1,   2,   0,   4],
       ..., 
       [154, 140, 135, 142],
       [154, 142, 140, 155],
       [155, 142, 154, 136]], dtype=int32))
('feed_dict(faces)[1]:', (1848, 4), array([[  0, 156, 157, 169],
       [  0, 157, 156, 248],
       [156, 157,   0, 158],
       ..., 
       [617, 559, 142, 612],
       [617, 612, 155, 559],
       [612, 559, 136, 617]], dtype=int32))
('feed_dict(faces)[2]:', (7392, 4), array([[   0,  618,  619,  658],
       [   0,  619,  618,  958],
       [ 618,  619,    0,  620],
       ..., 
       [2464, 2463,  617, 2465],
       [2465, 2463,  559, 2464],
       [2464, 2465,  612, 2463]], dtype=int32))
  and 4 dimensions means?
However, in 4_make_auxiliary_dat_file.ipynb, faces:
('face0:', (308, 3), array([[  0,   1,   2],
       [  1,   3,   4],
       [  2,   1,   4],
       ...,
       [155, 142, 154],
       [142, 155, 136]]))
('face1:', (1232, 3), array([[  0, 156, 157],
       [  1, 156, 163],
       [  2, 157, 163],
       ..., 
       [142, 578, 597],
       [155, 580, 597],
       [578, 580, 597]], dtype=int32))
('face2:', (4928, 3), array([[   0,  618,  619],
       [ 156,  618, 1081],
       [ 157,  619, 1081],
       ..., 
       [ 580, 2348, 2354],
       [ 597, 2404, 2354],
       [2348, 2404, 2354]], dtype=int32))
Thank you!  
Look forward to your reply!

**Comment by walsvid** [comment]
Hi @caixialiu-bjut , sorry for this. It is a bug, I have update the code.

**Comment by walsvid** [comment]
Please check the new script. Feel free to reopen this issue if you still meet some bug.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
