### ISSUE TITLE
eval_testset.py cannot work

### ISSUE THREAD

**Issue by woolpeeker** [nywang16/Pixel2Mesh#73]
the eval_testset.py try to import several module, but it do not exists.
`from pixel2mesh.models import GCN`
`from pixel2mesh.fetcher import *`
`from pixel2mesh.cd_dist import nn_distance`
There is only p2m module, and I changed the pixel2mesh to p2m. But I still cannot find the cd_dist module.
Thank you very much for any help .

**Comment by woolpeeker** [comment]
pixel2mesh.cd_dist should be p2m.chamfer.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
