### ISSUE TITLE
Question on EMD

### ISSUE THREAD

**Issue by YiruS** [nywang16/Pixel2Mesh#76]
Hi,

I have one question about the evaluation of EMD. In eval_testset.py line 147, the EMD is being multiplied by 0.01. Is there any reason of using 0.01? Is it data set dependent or any other considderation?

Thanks so much!
Yiru

**Comment by walsvid** [comment]
Hi, the reason of using 0.01 is to make the result consistent with previous work and make the comparison more fair.

**Comment by YiruS** [comment]
Just to be clear, so 0.01 functions as the normalization. And some other
number, i.e. 0.001 would also work?

**Comment by walsvid** [comment]
Yes, it is only to unify the units used for comparison in each paper.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
