### ISSUE TITLE
about number of GCN hidden layer units

### ISSUE THREAD

**Issue by fififei** [nywang16/Pixel2Mesh#81]
Hello, I have a question about the number of GCN hidden layer units.
Why you set it as 256, is there have any reason? Thx

**Comment by walsvid** [comment]
The reason for choosing such a number of models is more of a manual setting, and it is possible to choose other quantities as well. Feel free to reopen issue if you have other questions.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
