### ISSUE TITLE
Traning another data of Shapenet

### ISSUE THREAD

**Issue by zyqz97** [nywang16/Pixel2Mesh#86]
I found we can generate new data for training this network through Pixel2Mesh-master/GenerateData. I download the ShapeNetCore.v1 dataset and then use the scripts 1_sample_points.txt and 2_generate_normal.py to generate the point cloud of model.obj in ShapeNet. 
But there is some problem that I try to run the third scripts (3_camera_transform.py), it needs input  rendering_metadata.txt. However, in original Shapenet dataset, there is no file name rendering_metadata.txt. 
How can I get the rendering_metadata.txt?  or I just need to copy the exsit TXT flie to all the directory? 
For example: copy the exsit flie "Pixel2Mesh/GenerateData/1a0bc9ab92c915167ae33d942430658c/rendering/rendering_metadata.txt" to my own directory "02876657/109d55a137c042f5760315ac3bf2c13e/"

**Comment by zyqz97** [comment]
> 
> 
> I found we can generate new data for training this network through Pixel2Mesh-master/GenerateData. I download the ShapeNetCore.v1 dataset and then use the scripts 1_sample_points.txt and 2_generate_normal.py to generate the point cloud of model.obj in ShapeNet.
> But there is some problem that I try to run the third scripts (3_camera_transform.py), it needs input rendering_metadata.txt. However, in original Shapenet dataset, there is no file name rendering_metadata.txt.
> How can I get the rendering_metadata.txt? or I just need to copy the exsit TXT flie to all the directory?
> For example: copy the exsit flie "Pixel2Mesh/GenerateData/1a0bc9ab92c915167ae33d942430658c/rendering/rendering_metadata.txt" to my own directory "02876657/109d55a137c042f5760315ac3bf2c13e/"

The copy operation means I use the same "rendering_metadata.txt" to run the  scripts (3_camera_transform.py). Dose it affect the network performance?

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
