### ISSUE TITLE
How to generate .dat File from existing .xyz File? 

### ISSUE THREAD

**Issue by zyqz97** [nywang16/Pixel2Mesh#87]
Hello everyone.
I have some questions about data generate.
I have download Shapenet dataset. After sampling, normal generating and camera transforming, I get the different views XYZ file. But how can I transform XYZ file to the format .dat?

**Comment by walsvid** [comment]
Hi, @zyqz97. We use the standard library `pickle` in Python to serialize data to .dat files.

**Comment by zyqz97** [comment]
@walsvid  Could you share the serialize script?

**Comment by zyqz97** [comment]
**I try serialize  by the script below :**
with open('00.xyz','r',encoding='utf-8') as fin, .open('00.dat','wb') as fout:
                  lines=fin.readlines()
                  pickle.dump(len(lines),fout)
                  for line in lines:
                              pickle.dump(line, fout)
**But the generated dat data can not use to run train.py** 
**It has error:**
**ValueError: Cannot feed value of shape () for Tensor u'Placeholder_2:0', which has shape '(?, 6)'**

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
