### ISSUE TITLE
This method can be applied to 3d face reconstruction?

### ISSUE THREAD

**Issue by marvin521** [nywang16/Pixel2Mesh#9]
Hi thanks for sharing the wonderful code. I am wondering whether this method can be used to 3d face reconstruction?  is there any possible problem when this method is applied to 3d face reconstruction? thanks.

**Comment by walsvid** [comment]
Of course, but you need to complete the face to the full head as ground truth in order to have ellipsoid-like initial mesh.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
